package resource

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/simfra-dev/terraform-provider-simfra/internal/client"
	"github.com/simfra-dev/terraform-provider-simfra/internal/providerdata"
)

var (
	_ resource.Resource                = &accountResource{}
	_ resource.ResourceWithImportState = &accountResource{}
)

type accountResource struct {
	client *client.Client
}

type accountResourceModel struct {
	AccountID          types.String `tfsdk:"account_id"`
	Bootstrap          types.String `tfsdk:"bootstrap"`
	BootstrapRegion    types.String `tfsdk:"bootstrap_region"`
	AvailabilityZones  types.List   `tfsdk:"availability_zones"`
	VpcCIDR            types.String `tfsdk:"vpc_cidr"`
	RootAccessKeyID    types.String `tfsdk:"root_access_key_id"`
	RootSecretAccessKey types.String `tfsdk:"root_secret_access_key"`
	CreatedAt          types.String `tfsdk:"created_at"`
}

func NewAccountResource() resource.Resource {
	return &accountResource{}
}

func (r *accountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account"
}

func (r *accountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Simfra account.",
		Attributes: map[string]schema.Attribute{
			"account_id": schema.StringAttribute{
				Description: "The 12-digit AWS account ID. Generated by Simfra if not specified.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"bootstrap": schema.StringAttribute{
				Description: "Bootstrap mode. Set to \"standard\" to create default VPC, subnets, and other resources on account creation.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"bootstrap_region": schema.StringAttribute{
				Description: "AWS region for bootstrap resources. Required when bootstrap is set.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"availability_zones": schema.ListAttribute{
				Description: "Availability zones for bootstrap. Defaults to the region's standard AZs.",
				Optional:    true,
				ElementType: types.StringType,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
			},
			"vpc_cidr": schema.StringAttribute{
				Description: "VPC CIDR block for bootstrap. Defaults to 172.31.0.0/16.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"root_access_key_id": schema.StringAttribute{
				Description: "Root user access key ID.",
				Computed:    true,
				Sensitive:   true,
			},
			"root_secret_access_key": schema.StringAttribute{
				Description: "Root user secret access key.",
				Computed:    true,
				Sensitive:   true,
			},
			"created_at": schema.StringAttribute{
				Description: "Account creation timestamp.",
				Computed:    true,
			},
		},
	}
}

func (r *accountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *providerdata.ProviderData, got: %T", req.ProviderData))
		return
	}
	r.client = data.Admin
}

func (r *accountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan accountResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := client.CreateAccountRequest{}
	if !plan.AccountID.IsNull() && !plan.AccountID.IsUnknown() {
		createReq.AccountID = plan.AccountID.ValueString()
	}
	if !plan.Bootstrap.IsNull() {
		createReq.Bootstrap = plan.Bootstrap.ValueString()
	}
	if !plan.BootstrapRegion.IsNull() {
		createReq.Region = plan.BootstrapRegion.ValueString()
	}
	if !plan.AvailabilityZones.IsNull() {
		var azs []string
		resp.Diagnostics.Append(plan.AvailabilityZones.ElementsAs(ctx, &azs, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.AvailabilityZones = azs
	}
	if !plan.VpcCIDR.IsNull() {
		createReq.VpcCIDR = plan.VpcCIDR.ValueString()
	}

	acct, err := r.client.CreateAccount(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating account", err.Error())
		return
	}

	plan.AccountID = types.StringValue(acct.AccountID)
	plan.RootAccessKeyID = types.StringValue(acct.RootAccessKeyID)
	plan.RootSecretAccessKey = types.StringValue(acct.RootSecretAccessKey)
	plan.CreatedAt = types.StringValue(acct.CreatedAt)

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *accountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state accountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	acct, err := r.client.GetAccount(ctx, state.AccountID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading account", err.Error())
		return
	}

	state.AccountID = types.StringValue(acct.AccountID)
	state.RootAccessKeyID = types.StringValue(acct.RootAccessKeyID)
	state.RootSecretAccessKey = types.StringValue(acct.RootSecretAccessKey)
	state.CreatedAt = types.StringValue(acct.CreatedAt)

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *accountResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "Account resources cannot be updated in-place. All attributes require replacement.")
}

func (r *accountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state accountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteAccount(ctx, state.AccountID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting account", err.Error())
	}
}

func (r *accountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("account_id"), req, resp)
}
